snyk/snyk-sbt-plugin

- lib/index.js
- package.json
Swaps `console.error` for `debug` (already standard across the `snyk` CLI)
> fix: add debug to inspect

- lib/index.js
- lib/parse-sbt.js
- test/fixtures/sbt-no-plugin-output.txt
- test/functional/sbt-plugin.test.js
> Fix Dependency Tree Task Command

- lib/parse-sbt.js
- test/functional/parse-sbt.test.js
as the backend doesn't need these anymore,
and it reduces the result json size by factor of ~3x
> feat: don't include `from` arrays in tree

- .travis.yml
- appveyor.yml
Drop node 4 as it is no longer supported
Check the travis and appveyor config
> feat: Drop node 4, add node 10

- .travis.yml
- package.json
Align semantic release to other plugins, it is no longer needed as a dep in package.json
> chore: Update semantic release process

- .github/ISSUE_TEMPLATE.md
- .travis.yml
Update issue info to request relevant info
> chore: Update  instructions to get sbt info

- package.json
Remove unnecessary tslib dependency from the plugin
> fix: remove tslib dependency

- .gitignore
- lib/sub-process.js
- package.json
- test/system/timeout.test.ts
Adds a timeout around the sbt sub process being spawned. 
reduce timeout and run system-tests, or link with CLI and run snyk on scala project
> fix: add timeout to subproc

- package.json
Remove unused packages as flagged by https://github.com/snyk/snyk-sbt-plugin/issues/40
> chore: Remove unused packages

- appveyor.yml
We normally only support java 7-9, removing 11
> fix: remove java 11

- lib/index.ts
- test/functional/sbt-plugin.test.ts
Fix building args for executing `sbt` command
Fix correct version range from `0.1.0 - 1.2.0` to `0.1.0 - 1.1.0`, so plugin will pick up correct `SnykSbtPlugin` version for project
> fix: version range and args

- package.json
Removes unused dependencies, see #40 and #41 
It seems like these dependencies were removed in #41 and then re-added in #42 (maybe because of merge conflicts)
> chore: Remove unused dependencies

- lib/index.ts
Add pluginFormatVersion to new plugin output
> fix: add packageFormatVersion to new plugin

- test/system/plugin.test.ts
Add a check for packageFormatVersion presence
> test: add a check for packageFormatVersion presence

- .travis.yml
- test/fixtures/testproj-0.13-native-packager/project/plugins.sbt
- test/system/plugin.test.ts
Add test to solution provided by @iravid for the plugin failing when native-packager plugin is present.
See https://github.com/snyk/snyk-sbt-plugin/commit/a3bf8a921cf223195497ffca68806c5e88c7d705
> fix: add test against native packager fixture

- package.json
Seems tslib used in run time and fails the installation by
`pnpm`.
Solves https://github.com/snyk/snyk/issues/667
> feat: move tslib to be part of the production dependencies

- .gitignore
- README.md
Update readme to show our supported node, java & sbt versions
> docs: update support matrix docs

- README.md
Also trigger a release of contributor PR
Fix docs formatting + release https://github.com/snyk/snyk-sbt-plugin/pull/58
> feat: Update docs to fix formatting

- .travis.yml
Use `SDKman` for switching between SDK versions
Kudos to @sfat
> chore: fix build for JDK=12 and switch to using SDKman

- package.json
- test/fixtures/testproj-coursier-1.3.3/build.sbt
- test/fixtures/testproj-coursier-1.3.3/project/build.properties
- test/fixtures/testproj-coursier-1.3.3/project/site.sbt
- test/fixtures/testproj-coursier-1.3.3/src/main/scala/example/Hello.scala
- test/fixtures/testproj-coursier-1.3.5/build.sbt
- test/fixtures/testproj-coursier-1.3.5/project/build.properties
- test/fixtures/testproj-coursier-1.3.5/project/site.sbt
- test/fixtures/testproj-coursier-1.3.5/src/main/scala/example/Hello.scala
- test/system/plugin.test.ts
Add tests for sbt 1.3.3 and 1.3.5
> test: add tests for latest sbt versions

- .circleci/config.yml
Add config.yml so we can move this repo to CircleCI from Travis
> chore: add circleci config

- lib/parse-sbt.ts
- lib/sub-process.ts
- package.json
Same as https://github.com/snyk/snyk-sbt-plugin/pull/146, only with added confidence.
> feat: [CLI-194] bumping shescape, adding hardening
