snyk/snyk-sbt-plugin

lib/index.js
test/functional/sbt-plugin.test.js

Double-dash arguments are now sent as an array of strings, split by spaces.
Supports older, string-string arguments as well, so no breaking change here.

feat: supporting args as an array

---

lib/index.js

Adds a logging of sbt errors when running with the debug (`-d`) flag.

chore: debug sbt errors according to -d flag

---

lib/index.js
test/functional/sbt-plugin.test.js

This fixes an issues where arguments passed to the `snyk` cli after a `--` are not making it through in any useful way to `sbt`.
Arguments to configure the environment, e.g. -Dsbt.log.noformat=true, are ignored when passed after the `dependencyTree` task name.

fix: pass argument to `sbt` before task name

---

lib/index.js
test/functional/sbt-plugin.test.js

When the system property sbt.log.noformat is not set to true, `sbt` generates color-enabled output, which breaks the plugin's parsing logic. Forcing sbt.log.noformat to true to enable plain output by default.

fix: force no formatting on sbt output

---

lib/index.js
test/system/plugin.test.js

instead of current 'An unknown error occurred.' when e.g. `sbt` is not in the PATH

snyk: append the error text to thrown errors

---

lib/index.js
lib/parse-sbt.js
lib/sub-process.js
package.json
test/fixtures/sbt-no-plugin-output.txt
test/functional/parse-sbt.test.js
test/system/plugin.test.js

When `sbt` execution ends with an error, the plugin used to reject with a string containing the stdout or stderr of the `sbt` process. This doesn't work well with the CLI, which expects proper `Error` objects on plugin failure. Now fixed!

fix: throw proper error on failing sbt execution

---

lib/parse-sbt.js

- removes unused `groupId` and `artifactId` from response
- the current dependency tree format is very verbose and this gives us a tiny bit more headroom for large projects

BREAKING CHANGE: drop unused groupId and artifactId attributes from response

---

.eslintrc
lib/sub-process.js
package.json

Adds logging to sub process running sbt. To see the debug logs run the system-tests with `DEBUG=snyk-sbt-plugin npm run test-system`
`DEBUG=snyk-sbt-plugin npm run test-system`
https://snyksec.atlassian.net/browse/BST-641

fix: add logging to sub process

---

lib/sub-process.js
test/fixtures/bad-project/build.sbt
test/fixtures/bad-project/project/build.properties
test/system/plugin.test.ts

If sbt doesn't know how to handle an issue, it will ask for user input. Snyk doesn't know what the correct solution is, so we quit the process, and output it to the user.
SBT output looks like this when it hangs:
```[info] Loading project definition from /Users/orsagie/snyk/snyk-sbt-plugin/test/fixtures/bad-project/project
[error] [/Users/orsagie/snyk/snyk-sbt-plugin/test/fixtures/bad-project/build.sbt]:1: identifier expected but ',' found.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

fix: quit if process requires input

---

lib/sub-process.ts

SBT projects may take much longer than 5 minutes to generate dependency tree. removing timeout by default.

fix: have no timeout by default

---

appveyor.yml
lib/index.ts
package.json
test/fixtures/testproj-1.2.8/project/site.sbt
test/functional/sbt-plugin.test.ts
test/system-windows/plugin.test.ts
test/system/plugin.test.ts

Partially enable system tests on appveyor
Windows version of the tree doesn't have the top level package as a first dep, so adding special test file for this.
Coursier support is not working and needs further debugging in another PR

fix: enable system tests on windows

---

lib/index.ts

- Check a file exists before passing it to sub process as otherwise it fails inside the process without a nice error

feat: add a debug warning if manifest is missing on disk

---

lib/index.ts
test/system/plugin.test.ts

Change the name of the handling plugin so it can be differentiated in the CLI analytics.

fix: rename new plugin name for analytics

---

package.json

Add `scala` folder to `files` key in `package.json` so it will pack it correctly

fix: add scala folder to files in package.json

---

.travis.yml
README.md
package.json

feat: support jdk 8-13 during build

---

scala/SnykSbtPlugin-0.1x.scala
scala/SnykSbtPlugin-1.2x.scala
test/fixtures/testproj-play-scala-seed-1.2.8/.gitignore
test/fixtures/testproj-play-scala-seed-1.2.8/build.sbt
test/fixtures/testproj-play-scala-seed-1.2.8/project/build.properties
test/fixtures/testproj-play-scala-seed-1.2.8/project/plugins.sbt
test/system/plugin.test.ts

Adds three new configuration keys, `web-assets`, `web-plugin` and `web-assets-test` to the denylist of config keys that are used in the Snyk sbt plugin (currently opt-in with `--sbt-graph`) to enable the plugin to work out of the box with Play Framework projects that use the standard Play plugin.
As per the instructions in #57:
* Create a new Play scala seed project: `sbt new playframework/play-scala-seed.g8`
* Accept the defaults; `cd play-scala-seed`
* Copy the Snyk sbt plugin from this PR to `project/SnykSbtPlugin.scala`
* Install the sbt-dependency-graph plugin locally on the project: `echo 'addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")' | tee --append project/plugins.sbt`
* Run `sbt snykRenderTree`
Fixes #57

Denylist PlayWeb configuration names with undefined config keys. Fixes #57

---

README.md
appveyor.yml

Adds clarification that the purpose of the plugin is not to be used as a standalone app, but instead use the Snyk CLI tool instead
#64

docs: clarify usage of plugin is not to be used as standalone

---

lib/index.ts
test/system/plugin.test.ts

Make scanning via `--sbt-graph` the default.
#67 
Ran first with latest `snyk` with no parameters
```
snyk test snyk-sbt-plugin/test/fixtures/testproj-0.13  > old_format.json
```
Second run with latest `snyk` with `--sbt-graph` parameter
```
snyk test snyk-sbt-plugin/test/fixtures/testproj-0.13 --sbt-graph --json > old_format_with_sbt-graph.json
```
Third test with locally modified `snyk-sbt-plugin`
```
node dist/cli/index test snyk-sbt-plugin/test/fixtures/testproj-0.13 --json > new_format.json
```
Performed a `diff` between the 3 files and no diff are showing

feat: scan with --sbt-graph by default

---

scala/SnykSbtPlugin-1.2x.scala

Reduces the output size of running the SBT task(s) by:
- Replacing pretty printed JSON with ugly printed JSON.
- Setting the task's log level to `warn` to reduce unnecessary noise.
At the beginning
Some users scanning large repositories saw `RangeError: Invalid string length` caused by concatenating too much output from the child process into a single string.

fix: reduce scala script output size

---

lib/parse-sbt.ts
lib/sub-process.ts
lib/version.ts
package.json
test/functional/parse-sbt.test.ts
test/functional/version.spec.ts

Removes the transfer of the sbt output as a single string and conversion into an array of strings to allow output larger than ~512mb.
parseSbtPluginResults()
This can be tested against an sbt project with a lot of modules with the same dependents to exceed 512mb of data.
It is necessary to increase heap sizes for sbt and node to be able to hit the limit:
export SBT_OPTS="-Xmx8G"
export NODE_OPTIONS="--max-old-space-size=8192"
This probably relates to [cli sbt issue](https://github.com/snyk/cli/issues/343)
Example of a rangeError overflow in the output String:
$ node -e "console.log(process.versions.v8)"
28 9.4.146.26-node.24
29 $ node -e "x=new String();x=x.padStart(1024*1024*499);console.log(x.length)"
30 523239424
31 $ sbt "-Dsbt.log.noformat=true" --sbt-dir ./.sbt --ivy ./.ivy2 --batch …

fix: do not accumulate output into a single string

---

lib/index.ts
package.json
test/functional/sbt-plugin.test.ts

`sbt dependencyTree` has a max output width of 40, and thus truncating the dependency coordinates. Incomplete output rows lead to False Positives (because of missing "evicted by" tag, truncated dependency versions, etc)
Setting `asciiGraphWidth := 999999999` gets us the full untouched report
Reference: https://support.snyk.io/hc/en-us/articles/9590215676189-Deeply-nested-Scala-projects-have-dependencies-truncated

fix: enhance sbt output width
